version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  flyway:
    build: .
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:

volumes:
  mariadb_data:
