spring:
    flyway:
        enabled: true
        url: jdbc:mysql://localhost:3306/studentdb
        user: studentuser
        password: studentpass
        locations: classpath:db/migration
    application:
        name: frl
    datasource:
        url: jdbc:mysql://localhost:3306/studentdb
        username: studentuser
        password: studentpass
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    doc:
        swagger-ui:
            enabled: true
            path: /swagger-ui.html
            url: /Frlapi.json
        api-docs:
            path: /v3/api-docs

